---
sudo: required
notifications:
  slack: mousehat:yugE3opa3X2VxwBo9Vq9rpD1
services:
  - docker
install: sudo apt-get install parallel 
jobs:
  include:
    - stage: build_all
      script: ./build-all.sh
      if: type = cron

    - stage: test
      script: ./test.sh
      if: type IN (pull_request)

    - stage: deploy
      script: ./push.sh
      if: type IN (push)
