---
sudo: required
notifications:
  email: true
services:
  - docker
install: apt-get install parallel 
jobs:
  include:
    - stage: build_all
      script: ./build-all.sh
      if: TRAVIS_EVENT_TYPE IN (cron)

    - stage: test
      script: ./test.sh
      if: type IN (pull_request)

    - stage: deploy
      script: ./push.sh
      if: type IN (push)
